version: "3.8"

services:
  milvus:
    image: milvusdb/milvus:v2.6.6
    container_name: milvus-standalone
    command: ["milvus", "run", "standalone"]
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./milvus-data:/var/lib/milvus
    depends_on:
      - etcd
      - minio

  etcd:
    image: quay.io/coreos/etcd:v3.5.5
    container_name: milvus-etcd
    command: >
      etcd
      --advertise-client-urls=http://0.0.0.0:2379
      --listen-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379"

  minio:
    image: minio/minio:RELEASE.2023-10-07T15-07-38Z
    container_name: milvus-minio
    command: minio server /data
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"

  insight:
    image: milvusdb/milvus-insight:latest
    container_name: milvus-insight
    ports:
      - "8000:3000"
    depends_on:
      - milvus
